/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsHelloTriangleRouteImport } from './routes/projects/hello-triangle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHelloTriangleRoute = ProjectsHelloTriangleRouteImport.update({
  id: '/projects/hello-triangle',
  path: '/projects/hello-triangle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/hello-triangle': typeof ProjectsHelloTriangleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/hello-triangle': typeof ProjectsHelloTriangleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/hello-triangle': typeof ProjectsHelloTriangleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/hello-triangle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/hello-triangle'
  id: '__root__' | '/' | '/projects/hello-triangle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsHelloTriangleRoute: typeof ProjectsHelloTriangleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/hello-triangle': {
      id: '/projects/hello-triangle'
      path: '/projects/hello-triangle'
      fullPath: '/projects/hello-triangle'
      preLoaderRoute: typeof ProjectsHelloTriangleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsHelloTriangleRoute: ProjectsHelloTriangleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
