/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsUniformIndexRouteImport } from './routes/projects/uniform/index'
import { Route as ProjectsMultiStageVariableIndexRouteImport } from './routes/projects/multi-stage-variable/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsUniformIndexRoute = ProjectsUniformIndexRouteImport.update({
  id: '/projects/uniform/',
  path: '/projects/uniform/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMultiStageVariableIndexRoute =
  ProjectsMultiStageVariableIndexRouteImport.update({
    id: '/projects/multi-stage-variable/',
    path: '/projects/multi-stage-variable/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/multi-stage-variable/': typeof ProjectsMultiStageVariableIndexRoute
  '/projects/uniform/': typeof ProjectsUniformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/multi-stage-variable': typeof ProjectsMultiStageVariableIndexRoute
  '/projects/uniform': typeof ProjectsUniformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/multi-stage-variable/': typeof ProjectsMultiStageVariableIndexRoute
  '/projects/uniform/': typeof ProjectsUniformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/multi-stage-variable/' | '/projects/uniform/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/multi-stage-variable' | '/projects/uniform'
  id:
    | '__root__'
    | '/'
    | '/projects/multi-stage-variable/'
    | '/projects/uniform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsMultiStageVariableIndexRoute: typeof ProjectsMultiStageVariableIndexRoute
  ProjectsUniformIndexRoute: typeof ProjectsUniformIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/uniform/': {
      id: '/projects/uniform/'
      path: '/projects/uniform'
      fullPath: '/projects/uniform/'
      preLoaderRoute: typeof ProjectsUniformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/multi-stage-variable/': {
      id: '/projects/multi-stage-variable/'
      path: '/projects/multi-stage-variable'
      fullPath: '/projects/multi-stage-variable/'
      preLoaderRoute: typeof ProjectsMultiStageVariableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsMultiStageVariableIndexRoute: ProjectsMultiStageVariableIndexRoute,
  ProjectsUniformIndexRoute: ProjectsUniformIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
