/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithSidebarRouteRouteImport } from './routes/_with-sidebar/route'
import { Route as WithSidebarIndexRouteImport } from './routes/_with-sidebar/index'
import { Route as TpViewerObjIndexRouteImport } from './routes/tp/viewer-obj/index'
import { Route as TpGravitySwarmIndexRouteImport } from './routes/tp/gravity-swarm/index'
import { Route as TpGameOfLifeIndexRouteImport } from './routes/tp/game-of-life/index'
import { Route as WithSidebarMultiStageVariableIndexRouteImport } from './routes/_with-sidebar/multi-stage-variable/index'
import { Route as WithSidebarTextureTexture1IndexRouteImport } from './routes/_with-sidebar/texture/texture-1/index'
import { Route as WithSidebarBufferVertexIndexRouteImport } from './routes/_with-sidebar/buffer/vertex/index'
import { Route as WithSidebarBufferUniformIndexRouteImport } from './routes/_with-sidebar/buffer/uniform/index'
import { Route as WithSidebarBufferStorageIndexRouteImport } from './routes/_with-sidebar/buffer/storage/index'
import { Route as WithSidebar3dCubeIndexRouteImport } from './routes/_with-sidebar/3d/cube/index'

const WithSidebarRouteRoute = WithSidebarRouteRouteImport.update({
  id: '/_with-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const WithSidebarIndexRoute = WithSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithSidebarRouteRoute,
} as any)
const TpViewerObjIndexRoute = TpViewerObjIndexRouteImport.update({
  id: '/tp/viewer-obj/',
  path: '/tp/viewer-obj/',
  getParentRoute: () => rootRouteImport,
} as any)
const TpGravitySwarmIndexRoute = TpGravitySwarmIndexRouteImport.update({
  id: '/tp/gravity-swarm/',
  path: '/tp/gravity-swarm/',
  getParentRoute: () => rootRouteImport,
} as any)
const TpGameOfLifeIndexRoute = TpGameOfLifeIndexRouteImport.update({
  id: '/tp/game-of-life/',
  path: '/tp/game-of-life/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithSidebarMultiStageVariableIndexRoute =
  WithSidebarMultiStageVariableIndexRouteImport.update({
    id: '/multi-stage-variable/',
    path: '/multi-stage-variable/',
    getParentRoute: () => WithSidebarRouteRoute,
  } as any)
const WithSidebarTextureTexture1IndexRoute =
  WithSidebarTextureTexture1IndexRouteImport.update({
    id: '/texture/texture-1/',
    path: '/texture/texture-1/',
    getParentRoute: () => WithSidebarRouteRoute,
  } as any)
const WithSidebarBufferVertexIndexRoute =
  WithSidebarBufferVertexIndexRouteImport.update({
    id: '/buffer/vertex/',
    path: '/buffer/vertex/',
    getParentRoute: () => WithSidebarRouteRoute,
  } as any)
const WithSidebarBufferUniformIndexRoute =
  WithSidebarBufferUniformIndexRouteImport.update({
    id: '/buffer/uniform/',
    path: '/buffer/uniform/',
    getParentRoute: () => WithSidebarRouteRoute,
  } as any)
const WithSidebarBufferStorageIndexRoute =
  WithSidebarBufferStorageIndexRouteImport.update({
    id: '/buffer/storage/',
    path: '/buffer/storage/',
    getParentRoute: () => WithSidebarRouteRoute,
  } as any)
const WithSidebar3dCubeIndexRoute = WithSidebar3dCubeIndexRouteImport.update({
  id: '/3d/cube/',
  path: '/3d/cube/',
  getParentRoute: () => WithSidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WithSidebarIndexRoute
  '/multi-stage-variable/': typeof WithSidebarMultiStageVariableIndexRoute
  '/tp/game-of-life/': typeof TpGameOfLifeIndexRoute
  '/tp/gravity-swarm/': typeof TpGravitySwarmIndexRoute
  '/tp/viewer-obj/': typeof TpViewerObjIndexRoute
  '/3d/cube/': typeof WithSidebar3dCubeIndexRoute
  '/buffer/storage/': typeof WithSidebarBufferStorageIndexRoute
  '/buffer/uniform/': typeof WithSidebarBufferUniformIndexRoute
  '/buffer/vertex/': typeof WithSidebarBufferVertexIndexRoute
  '/texture/texture-1/': typeof WithSidebarTextureTexture1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WithSidebarIndexRoute
  '/multi-stage-variable': typeof WithSidebarMultiStageVariableIndexRoute
  '/tp/game-of-life': typeof TpGameOfLifeIndexRoute
  '/tp/gravity-swarm': typeof TpGravitySwarmIndexRoute
  '/tp/viewer-obj': typeof TpViewerObjIndexRoute
  '/3d/cube': typeof WithSidebar3dCubeIndexRoute
  '/buffer/storage': typeof WithSidebarBufferStorageIndexRoute
  '/buffer/uniform': typeof WithSidebarBufferUniformIndexRoute
  '/buffer/vertex': typeof WithSidebarBufferVertexIndexRoute
  '/texture/texture-1': typeof WithSidebarTextureTexture1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-sidebar': typeof WithSidebarRouteRouteWithChildren
  '/_with-sidebar/': typeof WithSidebarIndexRoute
  '/_with-sidebar/multi-stage-variable/': typeof WithSidebarMultiStageVariableIndexRoute
  '/tp/game-of-life/': typeof TpGameOfLifeIndexRoute
  '/tp/gravity-swarm/': typeof TpGravitySwarmIndexRoute
  '/tp/viewer-obj/': typeof TpViewerObjIndexRoute
  '/_with-sidebar/3d/cube/': typeof WithSidebar3dCubeIndexRoute
  '/_with-sidebar/buffer/storage/': typeof WithSidebarBufferStorageIndexRoute
  '/_with-sidebar/buffer/uniform/': typeof WithSidebarBufferUniformIndexRoute
  '/_with-sidebar/buffer/vertex/': typeof WithSidebarBufferVertexIndexRoute
  '/_with-sidebar/texture/texture-1/': typeof WithSidebarTextureTexture1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/multi-stage-variable/'
    | '/tp/game-of-life/'
    | '/tp/gravity-swarm/'
    | '/tp/viewer-obj/'
    | '/3d/cube/'
    | '/buffer/storage/'
    | '/buffer/uniform/'
    | '/buffer/vertex/'
    | '/texture/texture-1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/multi-stage-variable'
    | '/tp/game-of-life'
    | '/tp/gravity-swarm'
    | '/tp/viewer-obj'
    | '/3d/cube'
    | '/buffer/storage'
    | '/buffer/uniform'
    | '/buffer/vertex'
    | '/texture/texture-1'
  id:
    | '__root__'
    | '/_with-sidebar'
    | '/_with-sidebar/'
    | '/_with-sidebar/multi-stage-variable/'
    | '/tp/game-of-life/'
    | '/tp/gravity-swarm/'
    | '/tp/viewer-obj/'
    | '/_with-sidebar/3d/cube/'
    | '/_with-sidebar/buffer/storage/'
    | '/_with-sidebar/buffer/uniform/'
    | '/_with-sidebar/buffer/vertex/'
    | '/_with-sidebar/texture/texture-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithSidebarRouteRoute: typeof WithSidebarRouteRouteWithChildren
  TpGameOfLifeIndexRoute: typeof TpGameOfLifeIndexRoute
  TpGravitySwarmIndexRoute: typeof TpGravitySwarmIndexRoute
  TpViewerObjIndexRoute: typeof TpViewerObjIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_with-sidebar': {
      id: '/_with-sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-sidebar/': {
      id: '/_with-sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithSidebarIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/tp/viewer-obj/': {
      id: '/tp/viewer-obj/'
      path: '/tp/viewer-obj'
      fullPath: '/tp/viewer-obj/'
      preLoaderRoute: typeof TpViewerObjIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tp/gravity-swarm/': {
      id: '/tp/gravity-swarm/'
      path: '/tp/gravity-swarm'
      fullPath: '/tp/gravity-swarm/'
      preLoaderRoute: typeof TpGravitySwarmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tp/game-of-life/': {
      id: '/tp/game-of-life/'
      path: '/tp/game-of-life'
      fullPath: '/tp/game-of-life/'
      preLoaderRoute: typeof TpGameOfLifeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-sidebar/multi-stage-variable/': {
      id: '/_with-sidebar/multi-stage-variable/'
      path: '/multi-stage-variable'
      fullPath: '/multi-stage-variable/'
      preLoaderRoute: typeof WithSidebarMultiStageVariableIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/_with-sidebar/texture/texture-1/': {
      id: '/_with-sidebar/texture/texture-1/'
      path: '/texture/texture-1'
      fullPath: '/texture/texture-1/'
      preLoaderRoute: typeof WithSidebarTextureTexture1IndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/_with-sidebar/buffer/vertex/': {
      id: '/_with-sidebar/buffer/vertex/'
      path: '/buffer/vertex'
      fullPath: '/buffer/vertex/'
      preLoaderRoute: typeof WithSidebarBufferVertexIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/_with-sidebar/buffer/uniform/': {
      id: '/_with-sidebar/buffer/uniform/'
      path: '/buffer/uniform'
      fullPath: '/buffer/uniform/'
      preLoaderRoute: typeof WithSidebarBufferUniformIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/_with-sidebar/buffer/storage/': {
      id: '/_with-sidebar/buffer/storage/'
      path: '/buffer/storage'
      fullPath: '/buffer/storage/'
      preLoaderRoute: typeof WithSidebarBufferStorageIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
    '/_with-sidebar/3d/cube/': {
      id: '/_with-sidebar/3d/cube/'
      path: '/3d/cube'
      fullPath: '/3d/cube/'
      preLoaderRoute: typeof WithSidebar3dCubeIndexRouteImport
      parentRoute: typeof WithSidebarRouteRoute
    }
  }
}

interface WithSidebarRouteRouteChildren {
  WithSidebarIndexRoute: typeof WithSidebarIndexRoute
  WithSidebarMultiStageVariableIndexRoute: typeof WithSidebarMultiStageVariableIndexRoute
  WithSidebar3dCubeIndexRoute: typeof WithSidebar3dCubeIndexRoute
  WithSidebarBufferStorageIndexRoute: typeof WithSidebarBufferStorageIndexRoute
  WithSidebarBufferUniformIndexRoute: typeof WithSidebarBufferUniformIndexRoute
  WithSidebarBufferVertexIndexRoute: typeof WithSidebarBufferVertexIndexRoute
  WithSidebarTextureTexture1IndexRoute: typeof WithSidebarTextureTexture1IndexRoute
}

const WithSidebarRouteRouteChildren: WithSidebarRouteRouteChildren = {
  WithSidebarIndexRoute: WithSidebarIndexRoute,
  WithSidebarMultiStageVariableIndexRoute:
    WithSidebarMultiStageVariableIndexRoute,
  WithSidebar3dCubeIndexRoute: WithSidebar3dCubeIndexRoute,
  WithSidebarBufferStorageIndexRoute: WithSidebarBufferStorageIndexRoute,
  WithSidebarBufferUniformIndexRoute: WithSidebarBufferUniformIndexRoute,
  WithSidebarBufferVertexIndexRoute: WithSidebarBufferVertexIndexRoute,
  WithSidebarTextureTexture1IndexRoute: WithSidebarTextureTexture1IndexRoute,
}

const WithSidebarRouteRouteWithChildren =
  WithSidebarRouteRoute._addFileChildren(WithSidebarRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WithSidebarRouteRoute: WithSidebarRouteRouteWithChildren,
  TpGameOfLifeIndexRoute: TpGameOfLifeIndexRoute,
  TpGravitySwarmIndexRoute: TpGravitySwarmIndexRoute,
  TpViewerObjIndexRoute: TpViewerObjIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
